version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - .env.local
    volumes:
      - ./data:/var/lib/postgresql/data
